In [1]:
import pandas as pd

In [2]:
ratings = pd.read_csv('ratings.csv')

In [3]:
movies = pd.read_csv('movies.csv')

In [4]:
ratings = pd.merge(movies, ratings).drop(['genres','timestamp'], axis=1)

In [5]:
ratings["title"] = ratings["title"].str.lower()
ratings["title"] = ratings["title"].str.replace(r"\(.*\)","")

/var/folders/pn/9jrl5rsn6dq371sdff44k3hr0000gn/T/ipykernel_12208/1046905721.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  ratings["title"] = ratings["title"].str.replace(r"\(.*\)","")

In [6]:
user_ratings = ratings.pivot_table(index=['title'],columns=['userId'],values='rating')

In [7]:
user_ratings

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
title,,,,,,,,,,,,,,,,,,,,,
,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5
'71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
"'burbs, the",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'hellboy': the seeds of creation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'night mother,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zoom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.5,NaN,NaN,NaN,NaN,NaN
zootopia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
zulu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
¡three amigos!,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
à nous la liberté,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
user_ratings = user_ratings.dropna(thresh=10,axis=0).fillna(0)

In [9]:
user_ratings

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
title,,,,,,,,,,,,,,,,,,,,,
,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5
"'burbs, the",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10 cloverfield lane,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
10 things i hate about you,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0
"10,000 bc",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zodiac,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
zombieland,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5
zoolander,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,4.0
zootopia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
¡three amigos!,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
similarities_df = user_ratings.T.corr(method='pearson')

In [11]:
similarities_df

title,,"'burbs, the",10 cloverfield lane,10 things i hate about you,"10,000 bc",101 dalmatians,12 angry men,12 years a slave,127 hours,13 going on 30,...,young guns ii,young sherlock holmes,zack and miri make a porno,zero dark thirty,zero effect,zodiac,zombieland,zoolander,zootopia,¡three amigos!
title,,,,,,,,,,,,,,,,,,,,,
,1.000000,0.063117,0.142471,0.273989,0.193960,0.158751,0.160679,0.135486,0.200135,0.297152,...,0.053263,0.053021,0.374515,0.178655,0.068407,0.414585,0.355723,0.252226,0.216007,0.125905
"'burbs, the",0.063117,1.000000,-0.023768,0.143482,0.011998,0.169190,0.034133,0.009277,0.008331,0.049700,...,0.088114,0.257195,0.017477,0.032470,0.134701,0.153158,0.101301,0.049897,0.003233,0.353194
10 cloverfield lane,0.142471,-0.023768,1.000000,-0.005799,0.112396,0.002605,0.031619,-0.024275,0.272943,-0.027835,...,0.048452,0.028247,0.242663,0.099059,-0.023477,0.272347,0.241751,0.195054,0.319371,0.002733
10 things i hate about you,0.273989,0.143482,-0.005799,1.000000,0.244670,0.256865,0.013083,0.091964,0.043383,0.321071,...,0.045664,0.087961,0.243118,0.104858,0.132460,0.091853,0.158637,0.281934,0.050031,0.110612
"10,000 bc",0.193960,0.011998,0.112396,0.244670,1.000000,0.231937,0.059068,-0.025882,0.089328,0.167098,...,0.028153,0.040140,0.260261,0.087592,0.094913,0.184521,0.242299,0.240231,0.094773,0.083518
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zodiac,0.414585,0.153158,0.272347,0.091853,0.184521,0.068581,0.241083,0.190366,0.364841,0.134812,...,0.109848,0.068541,0.412563,0.231543,0.073237,1.000000,0.412975,0.242033,0.214385,0.189795
zombieland,0.355723,0.101301,0.241751,0.158637,0.242299,0.156524,0.145856,0.104150,0.198926,0.108230,...,0.066862,0.063131,0.443045,0.221367,0.059565,0.412975,1.000000,0.299522,0.298504,0.161397
zoolander,0.252226,0.049897,0.195054,0.281934,0.240231,0.287585,0.121873,0.017351,0.091416,0.225685,...,0.049861,0.078439,0.304364,0.243820,-0.006269,0.242033,0.299522,1.000000,0.108147,0.109455
zootopia,0.216007,0.003233,0.319371,0.050031,0.094773,0.080733,0.056603,0.063325,0.225747,0.069602,...,0.022403,0.034548,0.286213,0.156603,0.011418,0.214385,0.298504,0.108147,1.000000,0.020595
¡three amigos!,0.125905,0.353194,0.002733,0.110612,0.083518,0.132085,0.102563,0.004213,0.002912,0.021094,...,0.339847,0.296262,0.112808,0.064908,0.159929,0.189795,0.161397,0.109455,0.020595,1.000000

In [12]:
import joblib

In [13]:
joblib.dump(similarities_df, 'similarities.pkl')

['similarities.pkl']

In [20]:
moviesData=ratings.drop(['userId','rating'],axis=1)
moviesData=moviesData.drop_duplicates()
moviesData=moviesData.sort_values("movieId")
moviesData=moviesData.reset_index(drop=True)
moviesData["title"] = moviesData["title"].str.lower() 
moviesData["title"] = moviesData["title"].str.replace(r"\(.*\)","")
moviesData.head()

/var/folders/pn/9jrl5rsn6dq371sdff44k3hr0000gn/T/ipykernel_8474/3653894651.py:6: FutureWarning: The default value of regex will change from True to False in a future version.
  moviesData["title"] = moviesData["title"].str.replace(r"\(.*\)","")

   movieId                         title
0        1                    toy story
1        2                      jumanji
2        3             grumpier old men
3        4            waiting to exhale
4        5  father of the bride part ii

In [21]:
joblib.dump(moviesData, 'moviesData.pkl')

['moviesData.pkl']